### PR TITLE
(Feat) : Added +/- zoom control buttons for Workflow view 

### LINKED ISSUE #166: +/- zoom control buttons for Workflow view
The Workflow tab - specifically the Dependency Graph view - allows the user to zoom in and out on the generated graph using the scroll wheel of the mouse (this was a feature already enabled in the EChart library we use).

It's not apparent to users that they have the ability to zoom in and out.  We want to support the mouse wheel zooming, but also have visible buttons (suggested to use + and -) to also control the zooming.

image

### PR DESCRIPTION
**Pull request by Abhijay007**
# Summary of Changes

Implemented 'Zoom In' and 'Zoom Out' buttons for controlling DependencyGraph zoom, offering an alternative method alongside mouse scrolling.

## Related Issue

Closes #166 

## Checklist

- [x] My code is well-documented, and I've updated relevant documentation.
- [x] I have tested these changes on my local environment.
- [x] I have reviewed and proofread my code and the changes.
- [x] The branch is up-to-date with the base branch.

## Additional Context

https://github.com/StatTag/StatWrap/assets/64387054/13526fdc-153c-46f8-bb0b-d6db3edea3dd

## Reviewer(s)

@lrasmus

### CODE REVIEW

**Comment by lrasmus** [comment]
@Abhijay007 - this is looking amazing!!  One minor request - when the user clicks on the "Tree" option from the Workflow tab, could the "Zoom In" and "Zoom Out" buttons be hidden?  The "Tree" view (which admittedly isn't as exciting as the Dependency Graph) doesn't have zoom capabilities.

**Review by lrasmus — COMMENTED** [review]
Changes overall are great.  Thank you for taking the initiative to fix casing on component class names too.

**Comment by Abhijay007** [comment]
> @Abhijay007 - this is looking amazing!! One minor request - when the user clicks on the "Tree" option from the Workflow tab, could the "Zoom In" and "Zoom Out" buttons be hidden? The "Tree" view (which admittedly isn't as exciting as the Dependency Graph) doesn't have zoom capabilities.

sure @lrasmus I will do those changes

**Review by lrasmus — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
