### PR TITLE
Updates few project dependencies

### PR DESCRIPTION
**Pull request by AdiAkhileshSingh15**
# Changes Summary
This PR aims to update he existing dependencies to the latest LTS (Long Term Support) version.

The following dependencies have been updated: 

**devDependencies:**
1. **@babel/preset-env**: Updated to version `^7.24.0`
2. **chalk**: Updated to version `^4.1.2`
3. **css-loader**: Updated to version `^6.10.0`
4. **electron**: Updated to version `^29.1.1`
5. **electron-builder**: Updated to version `^24.13.3`
6. **fbjs-scripts**: Updated to version `^3.0.1`
7. **husky**: Updated to version `^9.0.11`
8. **lint-staged**: Updated to version `^15.2.2`
9. **react-test-renderer**: Updated to version `^18.2.0`
10. **rimraf**: Updated to version `^5.0.5`

**dependencies:**
1. **@mui/lab**: Updated to version `^5.0.0-alpha.167`
2. **github-markdown-css**: Updated to version `^5.5.1`

These tasks also include replacing the `@babel/plugin-proposal-private-property-in-object` with `plugin-transform-private-property-in-object`, as the npm suggests that `@babel/plugin-proposal-private-property-in-object` is deprecated. [source](https://www.npmjs.com/package/@babel/plugin-proposal-private-property-in-object?activeTab=code).

All the dependencies are updated to their latest LTS version, except for `chalk`.
As `chalk` LTS version v5 was giving some build and dev errors due to the way imports were being made in the module. 
"_IMPORTANT: Chalk 5 is ESM. If you want to use Chalk with TypeScript or a build tool, you will probably want to use Chalk 4 for now._"
I'd recommend you to go through this discussion. [Pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)
Though, I don't think keeping it to an old yet newer version is helpful in long-run. It would require us to move towards `dynamic imports` for ESM version.

Also, one small update in `github-markdown-css` requires us to specify import of light scheme of styling unlike the previous version. Actually, I came to know that it reads the `color-scheme `of the app or the specific component, I tried to set the color scheme that way, but it didn't help, so, specifying the module import came in pretty useful.

## Related Issue
Fixes: #171 

## Testing:
After updating dependencies, ran different checks using these commands locally to ensure functionality remains intact.
        Use commands:
- yarn test - all tests passed
- yarn dev - no UI fails detected
- yarn build - no build fails detected
- yarn dev - no new consol errors detected for any dependencies

## Reviewer(s)
@lrasmus

### CODE REVIEW

**Review by Abhijay007 — APPROVED** [review]
Looks good to me! 👍. One more thing @AdiAkhileshSingh15, could you please squash these commits into one?

**Comment by AdiAkhileshSingh15** [comment]
Yeah sure! @Abhijay007

**Comment by AdiAkhileshSingh15** [comment]
@Abhijay007 Can I take up some more dependency updates in this branch or do I need to get these merged to master first?
I'll ensure to squash the upcoming commits into one while I do so.

**Comment by Abhijay007** [comment]
> @Abhijay007 Can I take up some more dependency updates in this branch or do I need to get these merged to master first? I'll ensure to squash the upcoming commits into one while I do so.

sure @AdiAkhileshSingh15 you can add more dependency updates in this branch, just update that in both the issue list and PR description.

**Comment by AdiAkhileshSingh15** [comment]
Ohk sure! @Abhijay007

**Comment by AdiAkhileshSingh15** [comment]
Updating `stylelint` threw a console error, `Module build failed: Error: ENOENT: no such file or directory` which didn't affect the overall working of the application UI, neither did it face any build or test errors. 
This error came for some `unified` pkg, as it looked for a `is-plain-obj` folder, which was replaced by `is-buffer` folder in the node modules, most sources on the web suggested to reinstall the node modules or ignore this error.

Screenshot from 2024-03-09 17-35-25

**Comment by Abhijay007** [comment]
> Updating `stylelint` threw a console error, `Module build failed: Error: ENOENT: no such file or directory` which didn't affect the overall working of the application UI, neither did it face any build or test errors. This error came for some `unified` pkg, as it looked for a `is-plain-obj` folder, which was replaced by `is-buffer` folder in the node modules, most sources on the web suggested to reinstall the node modules or ignore this error.
> 
> Screenshot from 2024-03-09 17-35-25

@AdiAkhileshSingh15, thanks for looking into this but could you please try reinstalling the 'node modules' as the sources suggest? If errors persist afterward, it's better to revert this change. Although it may not directly impact the high-level functionality, it could be causing some hidden errors or issues.

**Comment by AdiAkhileshSingh15** [comment]
Screenshot from 2024-03-09 23-15-03
Reinstalling node modules alongwith restarting dev server cleaned the console 👍🏻  No more such `Module build failed: Error: ENOENT: no such file or directory` errors.

**Comment by lrasmus** [comment]
Sorry for the delays, thank you so much @AdiAkhileshSingh15 for the changes, and @Abhijay007 for keeping this going while I was away!

**Pull request merged**
