### PR TITLE
Revert "(Fix) : Fixed [Webpack] configuration to handle .cs files"

### PR DESCRIPTION
**Pull request by lrasmus**
Reverts StatTag/StatWrap#158

### CODE REVIEW

**Comment by lrasmus** [comment]
@Abhijay007 - unfortunately the PR didn't fix the issue for me.  When I pulled it down locally, I had the same error.

**Comment by Abhijay007** [comment]
> @Abhijay007 - unfortunately PR #158 didn't fix the issue for me. When I pulled it down locally, I had the same error.

@lrasmus it's strange, I tried it multiple times, no worries I will look into this.

**Comment by Abhijay007** [comment]
@lrasmus can you please share some screenshots for reference if possible, so that I can understand where is the issue,  I re-tried it with the same config, and it worked.

**Comment by lrasmus** [comment]
Sure thing - let me pull back down and redo.

**Comment by lrasmus** [comment]
@Abhijay007  - here are the steps that I used:

1. I applied the changes that you had made in PR #158 
2. From the project root I ran `rm -r node_modules/`
3. I then ran `yarn install`

And then got:

```
ERROR in ./node_modules/node-gyp/lib/Find-VisualStudio.cs 9:6
Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This script needs to be compatible with PowerShell v2 to run on Windows 2008R2 and Windows 7.
| 
> using System;
| using System.Text;
| using System.Runtime.InteropServices;
 @ ./node_modules/node-gyp/lib/ sync ^\.\/.*$ ./Find-VisualStudio.cs
 @ ./node_modules/node-gyp/lib/node-gyp.js 41:13-36 195:36-53
 @ ./node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js 9:35-54
 @ ./node_modules/@electron/rebuild/lib/src/module-rebuilder.js 34:19-52
 @ ./node_modules/@electron/rebuild/lib/src/rebuild.js 38:27-56
 @ ./node_modules/@electron/rebuild/lib/src/main.js 4:18-38
 @ dll renderer renderer[0]
```

**Pull request merged**
