### PR TITLE
Re-enable husky pre-commit hook

### LINKED ISSUE #195: Husky pre-commit hook not called
Recently noticed that the husky pre-commit hook (to run lint-staged) was no longer being called.  This is due to changes in how v9 of husky works.

### PR DESCRIPTION
**Pull request by lrasmus**
Fixes #195 
Update our project configuration so that husky's pre-commit hook is called and runs lint-staged.

### CODE REVIEW

**Comment by lrasmus** [comment]
@Abhijay007 and/or @AdiAkhileshSingh15  - there's no obligation, but would either of you be able to review this change?  I'm not sure if other setup steps are needed and want to confirm it works for you.

**Comment by AdiAkhileshSingh15** [comment]
@lrasmus Sure, I'll review it.

**Comment by AdiAkhileshSingh15** [comment]
@lrasmus, Changes look good. Could we possibly remove "git add" from the tasks in config to address the lint-staged warning?

**Comment by lrasmus** [comment]
Thank you @AdiAkhileshSingh15!  Let me take a look at the `git add` and play around with removing that, thanks for mentioning that.

**Comment by lrasmus** [comment]
Only took me 5 months to get back to this :P 

@AdiAkhileshSingh15 - no rush, but would you have time to review and make sure it works for you?

**Comment by AdiAkhileshSingh15** [comment]
Sure!

**Review by AdiAkhileshSingh15 — APPROVED** [review]
Reviewed all the changes. LGTM 🙌🏻

**Comment by lrasmus** [comment]
Thank you @AdiAkhileshSingh15 !

**Pull request merged**
